# load_module /opt/bitnami/nginx/modules/ngx_http_js_module.so;

# http {
js_import /opt/bitnami/nginx/conf/server_blocks/oauth2.js;

map $http_authorization $access_token {
  "~*^bearer (.*)$" $1;
  default $http_authorization;
}

server {
  listen 8080;
  root /app;
  index index.htm index.html;

  # error_log /tmp/nginx-error.log debug;

  location /products {
    proxy_pass https://dummyjson.com/products;    
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    # proxy_set_header Connection 'upgrade';
    # proxy_set_header Host $host;
    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;

    proxy_ignore_client_abort on;

    proxy_ssl_server_name on;         # Enables SNI support for backend
    proxy_ssl_protocols TLSv1.2 TLSv1.3;  # Ensures secure TLS versions
    proxy_ssl_verify off;             # Disable SSL verification (only if backend uses self-signed or untrusted certificates)    

    # proxy_no_cache    1;
    # proxy_cache_bypass  1;
    # expires -1;
    # add_header  Last-Modified $date_gmt;
    # add_header  Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    # if_modified_since off;
    # expires off;
    # etag  off;
    # proxy_buffering off; 

    # auth_basic "Restricted Content";
    # auth_basic_user_file /opt/bitnami/nginx/.htpasswd;

    auth_request /oauth2_token_introspection;
  }

  location = /oauth2_token_introspection {
        internal;
        js_content oauth2.introspectAccessToken ;
    }

  location = /oauth2_send_request {
    internal;

    # Enable decompression
    proxy_set_header Accept-Encoding "";
    # gunzip on;

    proxy_method      POST;
    proxy_set_header  Authorization "bearer SecretForOAuthServer";
    proxy_set_header  Content-Type "application/x-www-form-urlencoded";
    # add_header        X-token $http_token;
    proxy_set_body    "token=$access_token&client_id=<client_id>&client_secret=<client_secret>";
    proxy_pass        https://<KEYCLOAK_SERVER_URL>/auth/realms/<REAMS_NAME>/protocol/openid-connect/token/introspect;

    proxy_ssl_server_name on;         # Enables SNI support for backend
    proxy_ssl_protocols TLSv1.2 TLSv1.3;  # Ensures secure TLS versions
    proxy_ssl_verify off;             # Disable SSL verification (only if backend uses self-signed or untrusted certificates)

    # js_content introspectAccessToken ;

    proxy_cache_lock  on; # Don't allow simitaneous request for same token
    proxy_cache_valid 200 10s; # How long to use cache introspection response
    proxy_cache_use_stale error timeout; # Use old responses of cannot reach the server
    proxy_ignore_headers  Cache-Control Expires Set-Cookie; # Cacje even when receiving these

    # proxy_no_cache    1;
    # proxy_cache_bypass  1;
    # expires -1;
    # add_header  Last-Modified $date_gmt;
    # add_header  Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    # if_modified_since off;
    # expires off;
    # etag  off;
    # proxy_buffering off;
  }
}
# }